### PR TITLE
Fix order heights in PASSE and CUISINE

### LINKED ISSUE #98: Order height
Order height should be half of the screen

### PR DESCRIPTION
**Pull request by Xantass**
## Describe your changes
Fix order heights in PASSE and CUISINE
## Issue ticket number and link
Closes #98 
## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Documentation has been updated as required
If a single item in this checklist is not checked, the pull request cannot be accepted

### CODE REVIEW

File: src/Components/OrdersDisplay/SingleOrderDisplay.js [hunk 1]
```diff
@@ -147,10 +147,10 @@ export default function SingleOrderDisplay({ orderDetails, span, index, selectOr
   );
 
   return (
-    <div className={`h-full`}>
+    <div className={`h-full flex flex-col`}>
       {orderDetails ? (
-        <div>
-          <div className="bg-slate-600 text-white grid grid-cols-2 rounded-t-lg">
+        <div className={`h-full flex flex-col`}>
+          <div className="bg-slate-600 text-white grid grid-cols-2 rounded-t-lg flex-shrink-0" style={{ flexBasis: "20%" }}>
```
Comment (JulesGresset) [inline src/Components/OrdersDisplay/SingleOrderDisplay.js:153]: The header should not have a defined height but should hug the content instead.

**Review by JulesGresset — CHANGES_REQUESTED** [review]

**Review by JulesGresset — APPROVED** [review]
